"""
Django settings for crud_admin project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os, environ
env = environ.Env()
environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('CD_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('CD_DEBUG')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crud_app',
    'rest_framework',
    'corsheaders',
    'django_q',
    'import_export',
    'silk'
    # 'django.contrib.sites',
]

# SITE_ID=1
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware'
]

ROOT_URLCONF = 'crud_admin.urls'

#For only Nginx
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://*.evoluxar.com','https://*.127.0.0.1']

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crud_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('CD_DATABASE_ENGINE'),
        'NAME': env('CD_DATABASE_NAME'),
        'USER': env('CD_DATABASE_USER'),
        'PASSWORD': env('CD_DATABASE_PASSWORD'),
        'HOST': env('CD_DATABASE_HOST'),
        'PORT': env('CD_DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

#STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH=True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    # ]
}

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    'http://127.0.0.1:3000',
)

#setting.py changes
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# STATIC_ROOT  = os.path.join(BASE_DIR, 'staticfiles')
# STATIC_URL = '/static/'

# Extra lookup directories for collectstatic to find stsuatic files
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )

# Django-Q configuration
Q_CLUSTER = {
    'name': 'mycluster',
    'workers': 4,
    'timeout': 90,
    'retry': 300,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default',
    'retry_count': 5,
    'sync': False,
}

AWS_ACCESS_KEY_ID = env('CD_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('CD_AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('CD_AWS_STORAGE_BUCKET_NAME')
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
# AWS_DEFAULT_ACL = env('CD_AWS_DEFAULT_ACL')
AWS_S3_REGION_NAME = env('CD_AWS_S3_REGION_NAME')
AWS_S3_SIGNATURE_VERSION = env('CD_AWS_S3_SIGNATURE_VERSION')

# Use S3 for both static files and media files
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage"
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"
    }
}

AWS_LOCATION = 'media'  # This is where media files will be stored in the S3 bucket
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',  # Redis server address
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }


#Logger

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': '/data/logs/debug.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }

CD_SERVICES_SERVER_URL=env("CD_SERVICES_SERVER_URL")
CD_SSO_SERVER_URL=env("CD_SSO_SERVER_URL")

    
CD_ELASTIC_USER = env("CD_ELASTIC_USER")
CD_ELASTIC_SECRET = env("CD_ELASTIC_SECRET")
CD_CRUD_SERVER_URL = env("CD_CRUD_SERVER_URL")
CD_SSO_SERVER_URL = env("CD_SSO_SERVER_URL")
CD_DYNAMIC_SERVICES_SERVER_URL = env("CD_DYNAMIC_SERVICES_SERVER_URL")
CD_ELASTIC_HOST = env("CD_ELASTIC_HOST")
CD_ELASTIC_PORT = env("CD_ELASTIC_PORT")
SSO_ADMIN_USER_EMAIL = env("SSO_ADMIN_USER_EMAIL")
SSO_ADMIN_USER_PASSWORD = env("SSO_ADMIN_USER_PASSWORD")

CD_DYNAMIC_SERVICES_BRANCH = env("CD_DYNAMIC_SERVICES_BRANCH")